spring:
  profiles:
    active: dev
  cloud:
    gcp:
      trace:
        enabled: false
    openfeign:
      client:
        config:
          default:
            connectTimeout: 30000
            readTimeout: 60000
            follow-redirects: false

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

default:
  server:
    port: 48084
  datasource:
    url: 192.168.222.90
    port: 5432
    dbname: bpjsservice
    username: postgres
    password: G00gl3123

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always

app:
  name: "@project.name@"
  version: "@project.version@"
  desc: "@project.description@"

springdoc:
  swagger-ui:
    supported-submit-methods:
      - get

---
server:
  port: ${BPJSSERVICE_PORT:${default.server.port}}
  servlet:
    context-path: /${BPJSSERVICE_CONTEXT_PATH:bpjsservice}

spring:
  application:
    name: bpjsservice
  cloud:
    gcp:
      logging:
        enabled: true
  sql:
    init:
      platform: postgre
  datasource:
    url: jdbc:postgresql://${BPJSSERVICE_DATABASE_URL:${default.datasource.url}}:${BPJSSERVICE_DATABASE_PORT:${default.datasource.port}}/${BPJSSERVICE_DATABASE_NAME:${default.datasource.dbname}}
    username: ${BPJSSERVICE_DATABASE_USERNAME:${default.datasource.username}}
    password: ${BPJSSERVICE_DATABASE_PASSWORD:${default.datasource.password}}
    hikari:
      minimum-idle: 0
      max-lifetime: 60000
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: NON_NULL
  flyway:
    baseline-on-migrate: true

proxy:
  commonservice:
    host: ${COMMONSERVICE_HOST:${proxy.commonservice.url}}
    url: http://cluster.homtmh.local/commonservice
  vclaimrest:
    host: ${VCLAIMREST_HOST:${proxy.vclaimrest.url}}
    url: https://apijkn-dev.bpjs-kesehatan.go.id/vclaim-rest-dev
  aplicaresrest:
    host: ${APLICARESREST_HOST:${proxy.aplicaresrest.url}}
    url: https://new-api.bpjs-kesehatan.go.id/aplicaresws/rest
  antreanrs:
    host: ${ANTREANRS_HOST:${proxy.antreanrs.url}}
    url: https://apijkn-dev.bpjs-kesehatan.go.id/antreanrs_dev
  ihs:
    host: ${IHS_HOST:${proxy.ihs.url}}
    url: https://apijkn-dev.bpjs-kesehatan.go.id/ihs_dev

logging:
  threshold: ${LOGGING_THRESHOLD:5000}
---
spring:
  config:
    activate:
      on-profile:
        - dev
        - qa
  datasource:
    hikari:
      maximum-pool-size: 2

logging:
  level:
    org:
      springframework:
        web: WARN
      hibernate: INFO
    #'[com.rsmurniteguh.bpjs.bpjsservice.repository]': DEBUG #Uncomment untuk cek log mybatis
    #'[com.zaxxer.hikari]': DEBUG
---
spring:
  config:
    activate:
      on-profile:
        - prod
        - prd
  cloud:
    gcp:
      trace:
        enabled: true
  datasource:
    hikari:
      maximum-pool-size: 4

logging:
  level:
    root: ERROR
    "[com.rsmurniteguh.bpjs.bpjsservice.BpjsserviceApplication]": INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
